<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCreditNotesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('credit_notes', function (Blueprint $table) {
            $table->increments('id');
            $table->string('reference_no', 100)->nullable();
            $table->integer('client_id')->nullable();
            $table->enum('status', ['open', 'closed', 'void'])->default('open');
            $table->dateTime('sent_at')->nullable();
            $table->string('currency', 32)->default('USD');
            $table->mediumText('notes')->nullable();
            $table->mediumText('terms')->nullable();
            $table->decimal('tax', 10, 2)->nullable();
            $table->decimal('exchange_rate', 10, 5)->default(1.00000);
            $table->tinyInteger('is_refunded')->default(0);
            $table->timestamp('archived_at')->nullable();
            $table->decimal('amount', 10, 2)->default(0.00);
            $table->decimal('balance', 10, 2)->default(0.00);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('credit_notes');
    }
}
