<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAppointmentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('appointments', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('venue');
            $table->unsignedInteger('attendee_id')->nullable();
            $table->unsignedInteger('lead_id')->nullable();
            $table->dateTime('start_time')->nullable();
            $table->dateTime('finish_time')->nullable();
            $table->text('comments')->nullable();
            $table->integer('alert')->default(30);
            $table->timestamp('reminded_at')->nullable();
            $table->unsignedInteger('user_id')->nullable();
            $table->string('status')->default('R');
            $table->string('timezone')->default('Europe/London');
            $table->string('token')->nullable();
            $table->timestamps();
            $table->softDeletes();
            $table->index('deleted_at', 'appointments_deleted_at_index');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('appointments');
    }
}
