<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateFilesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('files', function (Blueprint $table) {
            $table->increments('id');
            $table->morphs('uploadable');
            $table->text('filename')->nullable();
            $table->string('title')->nullable();
            $table->string('adapter', 32)->default('local');
            $table->string('path')->nullable();
            $table->string('ext', 100)->nullable();
            $table->integer('size')->nullable();
            $table->tinyInteger('is_image')->default(0);
            $table->integer('image_width')->nullable();
            $table->integer('image_height')->nullable();
            $table->text('description')->nullable();
            $table->integer('user_id');
            $table->text('filelink');
            $table->string('handle')->nullable();
            $table->softDeletes();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('files');
    }
}
