<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTasksTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tasks', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name')->default('Task Name');
            $table->integer('project_id');
            $table->integer('milestone_id')->nullable();
            $table->mediumText('description')->nullable();
            $table->tinyInteger('visible')->default(0);
            $table->integer('progress')->default(0);
            $table->decimal('estimated_hours', 10, 2)->default(0.00);
            $table->tinyInteger('auto_progress')->default(1);
            $table->date('start_date')->nullable();
            $table->date('due_date')->nullable();
            $table->integer('user_id')->nullable();
            $table->integer('stage_id')->nullable();
            $table->timestamp('reminded_at')->nullable();
            $table->decimal('hourly_rate', 10, 2)->default(0.00);
            $table->bigInteger('time')->default(0);
            $table->tinyInteger('is_recurring')->default(0);
            $table->integer('recurred_from')->nullable();
            $table->timestamp('archived_at')->nullable();
            $table->softDeletes();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tasks');
    }
}
