<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateContractsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('contracts', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('client_id')->nullable();
            $table->string('contract_title')->nullable();
            $table->dateTime('start_date')->nullable();
            $table->dateTime('end_date')->nullable();
            $table->tinyInteger('rate_is_fixed')->default(0);
            $table->decimal('fixed_rate', 10, 2)->default(0.00);
            $table->decimal('hourly_rate', 10, 2)->default(0.00);
            $table->text('description')->nullable();
            $table->string('currency', 32)->default('USD');
            $table->string('license_owner', 32)->nullable();
            $table->dateTime('expiry_date')->nullable();
            $table->string('payment_terms', 64)->nullable();
            $table->decimal('late_payment_fee', 10, 2)->default(0.00);
            $table->tinyInteger('late_fee_percent')->default(1);
            $table->integer('termination_notice')->default(14);
            $table->decimal('cancelation_fee', 10, 2)->default(0.00);
            $table->tinyInteger('signed')->default(0);
            $table->timestamp('viewed_at')->nullable();
            $table->timestamp('sent_at')->nullable();
            $table->tinyInteger('is_visible')->default(0);
            $table->timestamp('rejected_at')->nullable();
            $table->text('rejected_reason')->nullable();
            $table->decimal('deposit_required', 10, 2)->default(0.00);
            $table->string('services')->nullable();
            $table->text('client_rights')->nullable();
            $table->tinyInteger('portfolio_rights')->default(1);
            $table->tinyInteger('non_compete')->default(1);
            $table->tinyInteger('feedbacks')->default(0);
            $table->tinyInteger('appropriate_conduct')->default(1);
            $table->text('annotations')->nullable();
            $table->integer('client_sign_id')->nullable();
            $table->integer('contractor_sign_id')->nullable();
            $table->integer('user_id');
            $table->timestamp('reminded_at')->nullable();
            $table->softDeletes();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('contracts');
    }
}
