<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateEmailsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('emails', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('to')->default(0);
            $table->integer('from')->default(0);
            $table->text('subject')->nullable();
            $table->longText('message')->nullable();
            $table->string('mail_folder')->default('INBOX');
            $table->text('meta')->nullable();
            $table->integer('reply_id');
            $table->tinyInteger('read')->default(0);
            $table->tinyInteger('is_draft')->default(0);
            $table->tinyInteger('opened')->default(0);
            $table->timestamp('reserved_at')->nullable();
            $table->morphs('emailable');
            $table->softDeletes();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('emails');
    }
}
