<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePluginsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('plugins', function (Blueprint $table) {
            $table->increments('id');
            $table->string('route', 155)->nullable();
            $table->string('name')->nullable();
            $table->string('title')->nullable();
            $table->longText('description')->nullable();
            $table->string('version', 45)->nullable();
            $table->string('author', 255)->nullable();
            $table->string('plugin_uri', 255)->nullable();
            $table->string('update_uri', 255)->nullable();
            $table->string('image_uri', 255)->nullable();
            $table->tinyInteger('installed')->default(0);
            $table->string('licence')->nullable();
            $table->integer('has_update')->nullable();
            $table->string('update_version', 20)->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('plugins');
    }
}
