<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDealsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('deals', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title')->nullable();
            $table->tinyInteger('stage_id')->nullable();
            $table->decimal('deal_value', 10, 2)->default(0.00);
            $table->integer('contact_person')->nullable();
            $table->integer('organization')->nullable();
            $table->dateTime('due_date')->nullable();
            $table->string('status', 32)->default('open');
            $table->dateTime('won_time')->nullable();
            $table->dateTime('lost_time')->nullable();
            $table->text('lost_reason')->nullable();
            $table->integer('source')->nullable();
            $table->tinyInteger('pipeline')->nullable();
            $table->string('currency', 64)->default('USD');
            $table->string('computed_value', 32)->default('$0.00');
            $table->decimal('todo_percent', 10, 2)->default(0.00);
            $table->tinyInteger('has_email')->default(0);
            $table->tinyInteger('has_activity')->default(0);
            $table->integer('days_to_close')->nullable();
            $table->date('next_followup')->nullable();
            $table->integer('user_id')->nullable();
            $table->timestamp('archived_at')->nullable();
            $table->softDeletes();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('deals');
    }
}
