<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateInvoicesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('invoices', function (Blueprint $table) {
            $table->increments('id');
            $table->string('reference_no', 64)->unique();
            $table->string('title')->nullable();
            $table->integer('client_id');
            $table->dateTime('due_date')->nullable();
            $table->text('notes')->nullable();
            $table->decimal('tax', 10, 2)->default(0.00)->nullable();
            $table->decimal('tax2', 10, 2)->default(0.00)->nullable();
            $table->decimal('discount', 10, 2)->default(0.00)->nullable();
            $table->string('currency', 32)->default('USD');
            $table->tinyInteger('alert_overdue')->default(1);
            $table->decimal('extra_fee', 10, 2)->default(0.00);
            $table->tinyInteger('fee_is_percent')->default(1);
            $table->decimal('exchange_rate', 10, 5)->default(1.00000);
            $table->string('status', 100)->default('not_paid');
            $table->decimal('payable', 10, 2)->default(0.00);
            $table->decimal('balance', 10, 2)->default(0.00);
            $table->decimal('tax_total', 10, 2)->default(0.00);
            $table->tinyInteger('discount_percent')->default(1);
            $table->decimal('paid_amount', 10, 2)->default(0.00);
            $table->integer('project_id')->nullable();
            $table->tinyInteger('is_locked')->default(0);
            $table->decimal('late_fee', 10, 2)->default(0.00);
            $table->tinyInteger('late_fee_percent')->default(1);
            $table->text('gateways')->nullable();
            $table->tinyInteger('is_recurring')->default(0);
            $table->tinyInteger('is_visible')->default(0);
            $table->integer('recurred_from')->nullable();
            $table->dateTime('viewed_at')->nullable();
            $table->timestamp('reminder1')->nullable();
            $table->timestamp('reminder2')->nullable();
            $table->timestamp('reminder3')->nullable();
            $table->dateTime('sent_at')->nullable();
            $table->dateTime('cancelled_at')->nullable();
            $table->timestamp('reminded_at')->nullable();
            $table->dateTime('archived_at')->nullable();
            $table->timestamps();
            $table->softDeletes();

            $table->index(['client_id', 'payable', 'balance'], 'invoices_client_date_saved_payable_balance_index');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('invoices');
    }
}
