<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePaymentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('payments', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code', 64)->unique();
            $table->integer('invoice_id');
            $table->integer('client_id');
            $table->string('payer_email', 100)->nullable();
            $table->integer('payment_method')->nullable();
            $table->string('currency', 64)->default('USD');
            $table->decimal('amount', 10, 2)->default(0.00);
            $table->string('amount_formatted', 64)->default('$0.00');
            $table->string('notes')->nullable();
            $table->integer('partial_id')->nullable();
            $table->timestamp('payment_date')->useCurrent();
            $table->text('meta')->nullable();
            $table->decimal('exchange_rate', 10, 5)->default(1.00000);
            $table->integer('project_id')->nullable();
            $table->tinyInteger('send_email')->default(1);
            $table->tinyInteger('is_refunded')->default(0);
            $table->timestamp('archived_at')->nullable();
            $table->timestamps();
            $table->softDeletes();
            $table->index('invoice_id', 'invoice');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('payments');
    }
}
