<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateClientsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('clients', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code', 32)->nullable();
            $table->tinyInteger('individual')->default(0);
            $table->string('name')->nullable();
            $table->integer('primary_contact')->nullable();
            $table->string('email', 64)->nullable();
            $table->string('website')->nullable();
            $table->string('phone', 64)->nullable();
            $table->string('mobile', 64)->nullable();
            $table->string('fax', 64)->nullable();
            $table->string('address1')->nullable();
            $table->string('address2')->nullable();
            $table->string('city', 100)->nullable();
            $table->string('state')->nullable();
            $table->string('locale', 10)->default('en');
            $table->string('country')->nullable();
            $table->string('tax_number', 64)->nullable();
            $table->string('zip_code', 20)->nullable();
            $table->string('currency', 32)->default('USD');
            $table->decimal('expense', 10, 2)->default('0.00');
            $table->decimal('balance', 10, 2)->default('0.00');
            $table->decimal('paid', 10, 2)->default('0.00');
            $table->string('skype')->nullable();
            $table->string('linkedin')->nullable();
            $table->string('facebook')->nullable();
            $table->string('twitter')->nullable();
            $table->text('notes')->nullable();
            $table->string('logo')->default('default_avatar.png');
            $table->integer('owner')->nullable();
            $table->string('slack_webhook_url')->nullable();
            $table->dateTime('unsubscribed_at')->nullable();
            $table->softDeletes();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('clients');
    }
}
