<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateIssuesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('issues', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code', 64)->unique();
            $table->integer('project_id')->nullable();
            $table->integer('user_id')->nullable();
            $table->integer('assignee')->nullable();
            $table->string('subject')->nullable();
            $table->string('reproducibility')->nullable();
            $table->string('severity', 100)->nullable();
            $table->string('priority', 100)->nullable();
            $table->text('description')->nullable();
            $table->tinyInteger('status')->nullable();
            $table->dateTime('closed_at')->nullable();
            $table->text('meta')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('issues');
    }
}
