<?php

return [
    'track_emails'             => env('EMAIL_TRACKING_ENABLE', true),
    'avatar_dir'               => env('AVATAR_DIR', 'public/avatars'),
    'signature_dir'            => env('SIGNATURE_DIR', 'public/signatures'),
    'logos_dir'                => env('LOGOS_DIR', 'public/logos'),
    'media_dir'                => env('MEDIA_DIR', 'public/media'),
    'pdf_font'                 => env('PDF_FONT', 'dejavusans'),
    'pdf'                      => [
        'invoices' => [
            'template' => env('INVOICE_PDF_TEMPLATE', 'default'),
        ],
    ],
    'verification'             => env('EMAIL_VERIFICATION', false),
    'secure_password'          => env('PWNED_PASSWORD', false),
    'imap_enabled'             => env('IMAP_ENABLED', true),
    'asset_cdn'                => env('ASSET_CDN', false),
    'daily_digest'             => [
        'enabled' => env('DAILY_DIGEST_ENABLED', true),
        'send_at' => env('DAILY_DIGEST_AT', '23:58'),
    ],
    'cashier'                  => [
        'currency' => env('SUBSCRIPTION_CURRENCY', 'USD'),
        'symbol'   => env('SUBSCRIPTION_SYMBOL', '$'),
    ],
    'activity_days'            => env('ACTIVITY_DAYS', 180),
    'delete_after'             => env('DELETE_AFTER', 360),
    'task_due_after'           => env('TASK_DUE_DAYS', 7),
    'budget_exceeds'           => env('BUDGET_EXCEEDS', 90),
    'remind_overdue_tasks'     => env('TASKS_REMIND_OVERDUE', true),
    'show_items_invoice_mail'  => env('SHOW_ITEMS_INVOICE_MAIL', false),
    'show_items_estimate_mail' => env('SHOW_ITEMS_ESTIMATE_MAIL', false),
    'logo_on_emails'           => false,
    'supported_locales'        => array(
        'en', 'fr', 'de', 'es',
    ),
    'alert_todo_before'        => env('ALERT_TODO_DAYS', '2'),
    'autoremind_contracts'     => env('AUTO_REMIND_CONTRACTS', true),
    'remind_contracts_before'  => env('CONTRACT_REMIND_DAYS', 2),
    'csv_max_file'             => 500000,
    'supported_currency_words' => array(
        'ALL', 'AUD', 'BAM', 'BGN', 'BRL', 'BYR', 'CAD', 'CHF', 'CYP', 'CZK', 'DKK',
        'EEK', 'EUR', 'GBP', 'HKD', 'HRK', 'HUF', 'ILS', 'ISK', 'JPY', 'LTL', 'LVL', 'MKD',
        'MTL', 'NOK', 'PLN', 'ROL', 'RUB', 'SEK', 'SIT', 'SKK', 'TRL', 'UAH', 'USD', 'YUM', 'ZAR',
    ),
    'telegram_bot_token'       => env('TELEGRAM_BOT_TOKEN', ''),
    'stripe_telegram_token'    => env('TELEGRAM_STRIPE_TOKEN', ''),
    'pusher_enabled'           => env('PUSHER_ENABLED', false),
    'drift_enabled'            => env('ENABLE_DRIFT', false),
    'crisp_enabled'            => env('ENABLE_CRISP', false),
    'enable_onesignal'         => env('ENABLE_ONESIGNAL', false),
    'enable_tawk'              => env('ENABLE_TAWK', false),
    'material_design'          => false,
    'contract_color'           => '#3869D4',
    'saleurl'                  => 'https://workice.com',
    'error_report_uri'         => 'https://desk.workice.com/api/v1/errors',
    'support_uri'              => 'https://desk.workice.com/api/v1/public-ticket',
];
